prometheus:
  metrics_port: 9090

kafka:
  version: "2.1.0"
  brokers:
    - "localhost:9092"
  consumer_groups:
    whitelist: ""  # Regex pattern for allowed consumer groups
    blacklist: "my-consumer-group-1"         

redis:
  address: "localhost"
  port: 6379

app:
  iteration_interval: 15s
  num_workers: 5
